### ISSUE TITLE
Lenguaje explícito y vulgar

### ISSUE THREAD

**Issue by nmilcoff** [gentilijuanmanuel/artificial-intelligence-final-exam#1]
Media pila chimuelo. Ya te forkee el repo, GG.

https://github.com/gentilijuanmanuel/artificial-intelligence-final-exam/blob/2fa58f3340f35b5a4d4a693c5c81e93b784b6614/finals/Clientes/final_clientes.pl#L34

**Comment by gentilijuanmanuel** [comment]
jajajajja

de una perro 🐕
